### ISSUE TITLE
Qiskit 0.8 and younger don't have QISKitError

### ISSUE THREAD

**Issue by aleksey-uvarov** [Qiskit/qiskit-qcgpu-provider#10]
Hello.

When I try to use the QCGPU provider with the most recent version of Qiskit, I see a "can't import 'QISKitError' from 'qiskit'" error. It seems that the problem is that that this module is deprecated:

https://qiskit.org/documentation/autodoc/qiskit.qiskiterror.html?highlight=qiskiterror#module-qiskit.qiskiterror

Thanks.

**Comment by ValentinS4t1qbit** [comment]
Qiskit has moved significantly but is now pretty stable after their all redesign. I think it would be a great time to fix integration issues to showcase the power of this simulator.

**Comment by adamisntdead** [comment]
Hello! I will fix this in the next few hours. I haven't been very active on this as I am doing a rewrite to a more general simulation framework, which includes some other types of simulator and hardware support.

**Comment by ValentinS4t1qbit** [comment]
Hello ! Just wondering if you'd have the time to have a quick look at this issue.

**Comment by jwoehr** [comment]
Probably some changes coming soon, @ValentinS4t1qbit . I submitted a pull request that probably is not exactly the right strategy to fix stuff like this, but you and I are both interested in this sort of simulation, so one supposes we'll fix it ourselves and submit PRs even if @adamisntdead has too much on his plate to deal with it very often.

**Comment by adamisntdead** [comment]
I am working! I'm moving to CUDA for extra speed, but I am getting this
usable with the OpenCL currently.

Great to see interest!

**Comment by ValentinS4t1qbit** [comment]
Cool ! 

With the architectural changes in the last generation of NVIDIA GPUs I wonder if the tensor units may not actually provide remarkable performance on other time of simulations that are a bit more tensor-product-based (which probably align with your current interests).

Porting what you have to CUDA does not look difficult since you're using very basic operations in your kernels, so you may get a leap in performance for a very reasonable effort.

IBM may or may not be rolling a CUDA and then MPI enabled simulator later this year, according to this PR, which apparently requires an ambitious review: https://github.com/Qiskit/qiskit-aer/pull/214

**Comment by adamisntdead** [comment]
Hello, I am closing this issue as I fixed it earlier. On your point about CUDA/MPI, I actually have the implementations complete, and it's just about getting it into the library at this point.
